### ISSUE TITLE
Install warning for maxmind

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-geodb#10]
Getting this: 

```
npm WARN engine maxmind@1.1.0: wanted: {"node":">=0.8.0","npm":"1"} (current: {"node":"4.4.7","npm":"2.15.8"})
```

Is it possible to fix this easily @TDA in the maxmind package ?

**Comment by pdehaan** [comment]
This is fixed in master in **maxmind** (see [**runk/node-maxmind** /package.json:43-46](https://github.com/runk/node-maxmind/blob/a6f070972e73a9a7e075198bef64da59d57c9d84/package.json#L43-L46)), but it isn't published to npm yet:

```js
  "engines": {
    "node": ">=0.8.0",
    "npm": ">=1"
  },
```

Filed upstream as https://github.com/runk/node-maxmind/issues/45

**Comment by vladikoff** [comment]
Thanks @pdehaan !!
