### ISSUE TITLE
mozlog used during normal install

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-geodb#11]
if you `npm install` the module you get

```
{"Timestamp":1469111003337000000,"Logger":"fxa-geodb","Type":"Download directory is /Users/vladikoff/tmp/test1/node_modules/fxa-geodb/db","Severity":6,"Pid":29847,"EnvVersion":"2.0"}
{"Timestamp":1469111003339000000,"Logger":"fxa-geodb","Type":"Adding https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz","Severity":6,"Pid":29847,"EnvVersion":"2.0"}
{"Timestamp":1469111003340000000,"Logger":"fxa-geodb","Type":"Setting /Users/vladikoff/tmp/test1/node_modules/fxa-geodb/db/cities-db.mmdb as target file","Severity":6,"Pid":29847,"EnvVersion":"2.0"}
{"Timestamp":1469111007344000000,"Logger":"fxa-geodb","Type":"unzip complete","Severity":6,"Pid":29847,"EnvVersion":"2.0"}
{"Timestamp":1469111007484000000,"Logger":"fxa-geodb","Type":"checking if lookup works with downloaded file","Severity":6,"Pid":29847,"EnvVersion":"2.0"}
{"Timestamp":1469111007489000000,"Logger":"fxa-geodb","Type":"lookup works, renaming downloaded file","Severity":6,"Pid":29847,"EnvVersion":"2.0"}
{"Timestamp":1469111007490000000,"Logger":"fxa-geodb","Type":"Downloads complete","Severity":6,"Pid":29847,"EnvVersion":"2.0"}
{"Timestamp":1469111007491000000,"Logger":"fxa-geodb","Type":"Last Update: Thu Jul 21 2016 10:23:27 GMT-0400 (EDT)","Severity":6,"Pid":29847,"EnvVersion":"2.0"}
```

@TDA I think mozlog should only be used when the updater is used via a process but not normal npm install. Otherwise it is not very readable during server installation.

**Comment by TDA** [comment]
@vladikoff Valid point, let me look into it :)

**Comment by vladikoff** [comment]
@TDA should we reassign this one?

**Comment by TDA** [comment]
@vladikoff I will do this 👍

**Comment by TDA** [comment]
@vladikoff What is the ideal way to proceed on this? Is there an easy way to figure out if a script is called as part of `npm install` ?

**Comment by vladikoff** [comment]
@TDA you can probably just pass an env variable, something like: `"postinstall": "LOG_FORMAT=something node scripts/start-db-download.js",` and disable mozlog if var is present

**Comment by jrgm** [comment]
> I think mozlog should only be used when the updater is used via a process but not normal npm install.

Side note: we have far too many issue manifest only in production due to running mozlog in a different mode in dev. Let's stop doing that.
