### ISSUE TITLE
Make path.parse compatible with node 0.10

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-geodb#16]
ref https://github.com/mozilla/fxa-geodb/blob/3469d3fc92c61f3120c7807cb6ac5e32a8b082f6/lib/maxmind-db-downloader.js#L55

**Comment by pdehaan** [comment]
Looks like [`path.parse()`](https://nodejs.org/api/path.html#path_path_parse_path) was added in Node 0.11:

```js
path.parse('/home/user/dir/file.txt')
// returns
// {
//    root : "/",
//    dir : "/home/user/dir",
//    base : "file.txt",
//    ext : ".txt",
//    name : "file"
// }
```

Kind of looks similar to [`path.basename()`](https://nodejs.org/api/path.html#path_path_basename_path_ext) with a specified extension (assuming we know the expected file extension):

```js
path.basename('/foo/bar/baz/asdf/quux.html')
  // returns 'quux.html'

path.basename('/foo/bar/baz/asdf/quux.html', '.html')
  // returns 'quux'
```

**Comment by TDA** [comment]
@pdehaan we are using path.parse so that we *do not* have to know the extension. If we were to hardcode the extension as `.gz` or `.gzip` I might as well use just `string.slice`.

**Comment by TDA** [comment]
@vladikoff and @pdehaan https://www.npmjs.com/package/path-parse is this a valid option?
