### ISSUE TITLE
Discuss maxmind update process in AWS

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-geodb#2]
It's not clear what the best strategy is to update the maxmind db

some issues:

- autoscale
- multiple servers
- redownloading the same geo db file
- docker paths?
- other?

need feedback from @jrgm !

**Comment by vladikoff** [comment]
Current download is here: https://github.com/TDA/fxa-geodb/blob/master/scripts/maxmind-db-downloader.js

**Comment by shane-tomlinson** [comment]
@TDA and I had a chat about this the other day. Maxmind updates their DB ~ 1x per month, on a Monday evening IIRC. It seems reasonable to me to just install the latest Maxmind DB whenever we spin up new auth-server/mailers. Auto-update introduces a vector that could cause the auth-server/mailer to fail mid-train. A new DB would be downloaded and run w/o first being tested. Who knows what sort of errors could crop up in the download/refresh process. OTOH, if we only install the Maxmind DB during the deployment process, it will be tested, it's integrity can be ensured, and we will have a reasonable level of confidence that we aren't broken.

**Comment by jrgm** [comment]
So, trying to remember what I said live on vidyo, but, roughly:

It seems to me, given a minimum one-week update frequency of maxmind db, and a two week cycle of fxa-auth releases, that we can just pull down a new maxmind db with each fxa-auth release. We would want to decouple fetching a new db from actual provisioning of an auth-server, so a background task, possibly in Lambda, would regularly pull down a new db and put it into an S3 bucket. The provisioning would fetch from this s3 bucket and place the db in, e.g., `/var/data/maxmind`. Auth-server configuration would be set to look for databases in that location. When running with docker images, a volume mount would make the data available at `/var/data/maxmind` within the container.
