### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-geodb#33]
I tagged version `1.0.0` last week but don't have permission to `npm publish`. When @vladikoff gets back we should poke him with a stick / ask him politely.

**Comment by vladikoff** [comment]
@philbooth added you to owners, @jrgm has access as well

**Comment by philbooth** [comment]
Ah, thanks @vladikoff! Sorry for interrupting your PTO!

**Comment by philbooth** [comment]
Published.
