### ISSUE TITLE
rename GOOGLE_NAMESERVERS to some other default

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-geodb#9]
not sure if the name GOOGLE_NAMESERVERS makes sense, shouldn't this indicate some kind of a `TEST_IP` or something?

**Comment by TDA** [comment]
@vladikoff The nameservers are those of Google, and if they do change, will take down approx. half of the internet. I believe we should give credit, but I am fine with a name change.

EDIT: Googling `Google nameservers` also pops this right at the top, so will make it clearer that way.

**Comment by vladikoff** [comment]
@TDA It's not about google, but the IP addresses. we are just using that ip to test geodb right? so it is a GEODB_TEST_IP ?
